method: onet
data:
  import: configs/data/clevr3d.yaml
  num_points: 256
model:
  encoder_latent: null
  max_density: 10
  decoder: slotted
  encoder: slot_conv
  rep_type: nerf3d
  obj_kernel: None
  value_dim: 3
  c_dim: 128
  h_dim: 128
  z_dim: 0
  coarsefine: True
  encoder_kwargs:
    i_dim: 3
    num_slots: 7
    slot_iters: 5
    downsample: 2
    att_height: 60
    att_width: 80
    use_camera_pos: True
    resnet: 'resnet18'
    self_attention: True
    explicit_bg: False
  decoder_kwargs:
    decoder_arch: 'nerf'
    net_arch: ain
    num_layers: 5
    hidden_size: 128
    coord_transform: False
    coord_transform_map: False
    view_dependent_values: True
    start_freq: -5
    num_freqs: 16
training:
  out_dir: 'HERE!'
  num_workers: 6
  lr_warmup: 0
  color_std: 0.2
  batch_size: 16
  model_selection_metric: loss
  model_selection_mode: minimize
  visualize_every: 5000
  validate_every: 5000
  backup_every: 25000
  grad_clip: 1.0
  trainer_kwargs:
    loss_type: 'nerf'
    depth_ll: 1.
test:
  threshold: 0.2
